name: dipdi-biases
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - astroid=2.15.6
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=23.1.0
  - autopep8=2.0.2
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.6.2
  - blis=0.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cachetools=5.3.1
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.6
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.1.0
  - cryptography=41.0.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.8
  - decorator=5.1.1
  - dill=0.3.7
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.12.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gdown=4.7.1
  - gettext=0.21.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - google-auth=2.22.0
  - google-auth-oauthlib=1.0.0
  - graphite2=1.3.13
  - grpcio=1.54.3
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2022.1.0
  - ipykernel=6.24.0
  - ipython=8.14.0
  - isort=5.12.0
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.0
  - jpeg=9e
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.9.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.0.149
  - libcups=2.3.3
  - libcurand=10.3.3.53
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libglu=9.0.0
  - libgomp=13.1.0
  - libgpg-error=1.47
  - libgrpc=1.54.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - markdown=3.4.4
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpg123=1.31.3
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=3.1
  - ninja=1.11.1
  - nspr=4.35
  - nss=3.89
  - numpy=1.25.2
  - oauthlib=3.2.2
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.1.3
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=4.21.12
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - py-opencv=4.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.11.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pylint=2.17.4
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=68.0.0
  - sip=6.7.11
  - six=1.16.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - svt-av1=1.4.1
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tensorboard=2.12.3
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.1
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.3.2
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - werkzeug=2.3.6
  - wheel=0.41.0
  - wrapt=1.15.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
